import "./globals.css";
import LayoutProvider from "./LayoutProvider";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LayoutProvider>
          <Toaster />
          {children}
        </LayoutProvider>
        {/* <Toaster position="top-right" /> */}
      </body>
    </html>
  );
}
